const API_BASE="";
let currentPage=1,currentFilter="all",currentDate="",totalPages=1;
(function(){const html=document.documentElement,toggle=document.querySelector("[data-theme-toggle]");let theme=matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light";html.setAttribute("data-theme",theme);if(toggle){toggle.textContent=theme==="dark"?"☀️":"🌙";toggle.addEventListener("click",()=>{theme=theme==="dark"?"light":"dark";html.setAttribute("data-theme",theme);toggle.textContent=theme==="dark"?"☀️":"🌙"})}})();
async function loadData(){const grid=document.getElementById("records-grid");grid.innerHTML='<div class="loading">데이터 불러오는 중...</div>';const params=new URLSearchParams({page:currentPage,limit:20,...(currentDate&&{date:currentDate}),...(currentFilter==="detected"&&{detected_only:"true"})});try{const res=await fetch(`${API_BASE}/api/detections?${params}`);if(!res.ok)throw new Error(`HTTP ${res.status}`);const data=await res.json();totalPages=Math.ceil(data.total/20)||1;renderStats(data.total,data.results);renderCards(data.results);updatePagination()}catch(e){grid.innerHTML=`<div class="loading">❌ 서버 연결 실패: ${e.message}</div>`;console.error(e)}}
function renderStats(total,results){document.getElementById("total-count").textContent=total;const detected=results.filter(r=>r.detected).length;document.getElementById("detected-count").textContent=detected;const today=new Date().toISOString().split("T")[0];document.getElementById("today-count").textContent=results.filter(r=>r.timestamp&&r.timestamp.startsWith(today)).length}
function renderCards(records){const grid=document.getElementById("records-grid");if(!records.length){grid.innerHTML='<div class="loading">📭 기록이 없습니다.</div>';return}grid.innerHTML=records.map(r=>{const badge=r.detected?'<span class="record-badge badge-detected">📬 우편물 감지</span>':'<span class="record-badge badge-none">📭 감지 없음</span>';const img=r.image_url?`<img class="record-img" src="${r.image_url}" alt="감지 이미지" loading="lazy" onerror="this.style.display='none'" />`:'<div class="record-img-placeholder">📷</div>';const conf=r.confidence?`${(r.confidence*100).toFixed(1)}%`:"-";const time=r.timestamp?new Date(r.timestamp).toLocaleString("ko-KR"):"-";return`<div class="record-card${r.detected?" detected":""}" onclick="openModal('${r.image_url||""}','${escapeHtml(r.gemini_result||"")}','${time}')">${img}<div class="record-info">${badge}<div class="record-label">${r.label||"미분류"}</div><div class="record-conf">신뢰도: ${conf}</div>${r.gemini_result?`<div class="record-gemini">💬 ${escapeHtml(r.gemini_result)}</div>"":""}<div class="record-time">🕐 ${time}</div></div></div>`}).join("")}
function escapeHtml(str){return str.replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function filterAll(){currentFilter="all";currentPage=1;document.getElementById("btn-all").classList.add("active");document.getElementById("btn-detected").classList.remove("active");loadData()}
function filterDetected(){currentFilter="detected";currentPage=1;document.getElementById("btn-detected").classList.add("active");document.getElementById("btn-all").classList.remove("active");loadData()}
function applyDateFilter(){currentDate=document.getElementById("date-filter").value;currentPage=1;loadData()}
function refreshData(){loadData()}
function prevPage(){if(currentPage>1){currentPage--;loadData()}}
function nextPage(){if(currentPage<totalPages){currentPage++;loadData()}}
function updatePagination(){document.getElementById("btn-prev").disabled=currentPage<=1;document.getElementById("btn-next").disabled=currentPage>=totalPages;document.getElementById("page-info").textContent=`${currentPage} / ${totalPages} 페이지`}
function openModal(imageUrl,desc,time){const modal=document.getElementById("image-modal"),img=document.getElementById("modal-img"),descEl=document.getElementById("modal-desc");if(imageUrl){img.src=imageUrl;img.style.display="block"}else{img.style.display="none"}descEl.textContent=desc?`💬 ${desc}\n🕐 ${time}`:`🕐 ${time}`;modal.classList.add("open")}
function closeModal(){document.getElementById("image-modal").classList.remove("open")}
document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});
setInterval(loadData,30000);
loadData();
